### ISSUE TITLE
NPE during ChangeForm generation

### ISSUE THREAD

**Issue by voropaevp** [snowplow-incubator/snowplow-event-generator#26] opened 2022-11-02 21:54 UTC
Config to reproduce
```
{
  "seed": 3
  "payloadsTotal": 10000
  "withRaw": false
  "withEnrichedTsv": true
  "withEnrichedJson": false
  "compress": false
  "payloadsPerFile": 1000
  "eventPerPayloadMin": 10
  "eventPerPayloadMax": 1000
  "duplicates": {
    "natProb": 0.0
    "synProb": 0.0
    "natTotal": 1
    "synTotal": 1
  }
  "timestamps": {
    "type": "Fixed"
    "at": "2022-10-02T21:01:01z"
  }
}
```

**Comment by colmsnowplow** [comment] 2023-03-10 11:13
Closing as duplicate of #27

**Closed by colmsnowplow** 2023-03-10 11:13 UTC

**Comment by colmsnowplow** [comment] 2023-03-13 13:22
Not sure what I meant to link to above - our CHANGELOG generation has gone haywire it seems. the issue was fixed here: https://github.com/snowplow-incubator/snowplow-event-generator/commit/304c416f394b5c30cb8682bb7bb901eca142aa4a
